#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooigo.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityRepository : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\View\EntityRepository.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\View\EntityRepository.cshtml"
                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");


            
            #line default
            #line hidden
WriteLiteral("namespace ");


            
            #line 6 "..\..\View\EntityRepository.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 6 "..\..\View\EntityRepository.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Repository\r\n{\r\n    using MyRow = Entities.");


            
            #line 8 "..\..\View\EntityRepository.cshtml"
                       Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n    using Dapper;\r\n    using Dapper.Contrib.Extensions;\r\n    using System.Coll" +
"ections.Generic;\r\n    using System.Data;\r\n    using Entities;\r\n    using System." +
"Linq;\r\n\r\n    public class ");


            
            #line 16 "..\..\View\EntityRepository.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral(@"Repository
    {

        public long Create(IUnitOfWork uow, SaveModel<MyRow> request)
        {
            return uow.Connection.Insert(request.Entity, transaction: uow.Transaction);
        }

        public bool Update(IUnitOfWork uow, SaveModel<MyRow> request)
        {
            return uow.Connection.Update(request.Entity, transaction: uow.Transaction);
        }

        public bool Delete(IUnitOfWork uow, DeleteModel<MyRow> request)
        {
            return uow.Connection.Delete(request.Entity, transaction: uow.Transaction);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            var model = connection.Query<MyRow>(""select * from [");


            
            #line 36 "..\..\View\EntityRepository.cshtml"
                                                            Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("] where \" + request.Filter.ToString() + request.Sort.ToOrderByString(), request.F" +
"ilter).ToList();\r\n            return new ListResponse<MyRow>()\r\n            {\r\n " +
"               Entities = model,\r\n            };\r\n        }\r\n\r\n\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
