#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooigo.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class FilterEntity : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\View\FilterEntity.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\View\FilterEntity.cshtml"
                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");


            
            #line default
            #line hidden
WriteLiteral("namespace ");


            
            #line 6 "..\..\View\FilterEntity.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 6 "..\..\View\FilterEntity.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Entities\r\n{\r\n    using System;\r\n    using System.Collections.Generic;\r\n    using" +
" System.Linq;\r\n    using System.Text;\r\n\r\n    public class ");


            
            #line 13 "..\..\View\FilterEntity.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden

            
            #line 13 "..\..\View\FilterEntity.cshtml"
                                   WriteLiteral("Filter : FilterEntity\r\n    {");

            
            #line default
            #line hidden
            
            #line 14 "..\..\View\FilterEntity.cshtml"
      foreach (var x1 in Model.Fields){

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n        public ");


            
            #line 16 "..\..\View\FilterEntity.cshtml"
          Write(x1.Type);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 16 "..\..\View\FilterEntity.cshtml"
                   Write(x1.Ident);

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }");


            
            #line 16 "..\..\View\FilterEntity.cshtml"
                                                      }

            
            #line default
            #line hidden
WriteLiteral("        \r\n        public override string ToString()\r\n        {\r\n            Strin" +
"gBuilder sb = new StringBuilder();\r\n            sb.Append(\" 1=1 \");\r\n");


            
            #line 22 "..\..\View\FilterEntity.cshtml"
             foreach (var x in Model.Fields)
            {
                if (x.Type == "Int32"
                    || x.Type == "Int64"
                    || x.Type == "Decimal"
                    || x.Type == "Boolean"
                    || x.Type == "Single"
                    || x.Type == "Double"
                    || x.Type == "Int16"
                    )
                {
            
            #line default
            #line hidden
WriteLiteral("\r\n            if (");


            
            #line 33 "..\..\View\FilterEntity.cshtml"
           Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral(" > 0)\r\n            {\r\n                sb.Append(\" and ");


            
            #line 35 "..\..\View\FilterEntity.cshtml"
                           Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("=");


WriteLiteral("@");


            
            #line 35 "..\..\View\FilterEntity.cshtml"
                                      Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral(" \");\r\n            }");

WriteLiteral("\r\n");


            
            #line 37 "..\..\View\FilterEntity.cshtml"
                }
                else if (x.Type == "String")
                {
            
            #line default
            #line hidden
WriteLiteral("\r\n            if (!string.IsNullOrWhiteSpace(");


            
            #line 40 "..\..\View\FilterEntity.cshtml"
                                      Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("))\r\n            {\r\n                sb.Append(\" and ");


            
            #line 42 "..\..\View\FilterEntity.cshtml"
                           Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("=");


WriteLiteral("@");


            
            #line 42 "..\..\View\FilterEntity.cshtml"
                                      Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("  \");\r\n            }");

WriteLiteral("\r\n");


            
            #line 44 "..\..\View\FilterEntity.cshtml"
                }
                else if (x.Type == "DateTime")
                {
            
            #line default
            #line hidden
WriteLiteral("\r\n            if (");


            
            #line 47 "..\..\View\FilterEntity.cshtml"
           Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral(" > DateTime.MinValue)\r\n            {\r\n                sb.Append(\" and ");


            
            #line 49 "..\..\View\FilterEntity.cshtml"
                           Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("=");


WriteLiteral("@");


            
            #line 49 "..\..\View\FilterEntity.cshtml"
                                      Write(x.Ident);

            
            #line default
            #line hidden
WriteLiteral("  \");\r\n            }");

WriteLiteral("\r\n");


            
            #line 51 "..\..\View\FilterEntity.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            return sb.ToString();\r\n        }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
